apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mutilate-agent
  namespace: mutilate
spec:
  serviceName: mutilate-agent-service
  replicas: 2
  selector:
    matchLabels:
      app: mutilate-agent
  template:
    metadata:
      labels:
        app: mutilate-agent
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: mutilate-agent
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchLabels:
                app: memcached
            topologyKey: kubernetes.io/hostname
      containers:
      - name: mutilate
        image: ghcr.io/m-sef/mutilate:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5556
        command:
        - '/bin/bash'
        - '-c'
        - >
          mutilate --agentmode --threads=16