#==============================================================================
# Author(s): m-sef (https://github.com/m-sef)
# Brief: Deploy mutilate leader as a single pod located on the master node
#==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: mutilate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutilate-leader-deployment
  namespace: mutilate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutilate-leader
  template:
    metadata:
      labels:
        app: mutilate-leader
    spec:
      nodeName: master.slmoore-309005.bayopsys-pg0.wisc.cloudlab.us 
      containers:
      - name: mutilate
        image: mutilate:latest
        # The Mutilate Docker image MUST be built locally on all nodes
        imagePullPolicy: Never
        command:
        - '/bin/bash'
        - '-c'
        - >
          sleep infinity
