#==============================================================================
# Author(s): Seth Moore (https://github.com/m-sef)
# Deploy mutilate leader as a single pod located on the master node
#==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: mutilate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mutilate-leader
  namespace: mutilate
spec:
  serviceName: mutilate-leader-service
  replicas: 1
  selector:
    matchLabels:
      app: mutilate-leader
  template:
    metadata:
      labels:
        app: mutilate-leader
    spec:
      nodeName: master
      containers:
      - name: mutilate
        image: ghcr.io/m-sef/mutilate:latest
        imagePullPolicy: Always
        command:
        - '/bin/bash'
        - '-c'
        - >
          sleep infinity
---
apiVersion: v1
kind: Service
metadata:
  name: mutilate-leader-service
  namespace: mutilate
spec:
  clusterIP: None
  selector:
    app: mutilate-leader