#==============================================================================
# Author(s): m-sef (https://github.com/m-sef)
# Brief: Deploy mutilate leader as a single pod located on the master node
#==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: mutilate
---
apiVersion: v1/apps
kind: Deployment
metadata:
  name: mutilate-deployment
  namespace: mutilate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutilate
    template:
      metadata:
        labels:
          app: mutilate
      spec:
        containers:
        - name: mutilate
          image: mutilate
          # The Mutilate Docker image MUST be built locally on all nodes
          imagePullPolicy: never