#==============================================================================
# Author(s): m-sef (https://github.com/m-sef)
# Brief: Deploy mutilate agent(s) as pod(s) which can not be colocated
#==============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: mutilate
---